name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    
    - name: Setup Poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: '1.4'
    
    - name: Set PyPI Credentials
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: poetry config pypi-token.pypi "$PYPI_TOKEN"
    
    - name: Install Dependencies
      run: poetry install -n --all-extras
    
    - name: Build package
      run: poetry publish --build

    - name: Publish Docs
      env:
        GIT_COMMITTER_NAME: ci-bot 
        GIT_COMMITTER_EMAIL: ci-bot@example.com
      run: poetry run mike deploy --push --update-aliases ${{ github.ref_name }} latest