name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    
    - name: Setup Poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: ${{ matrix.poetry-version }}
    
    - name: Set PyPI Credentials
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: poetry config pypi-token.pypi "$PYPI_TOKEN"
    
    - name: Install Dependencies
      run: poetry install --extras all
    
    - name: Build package
      run: poetry publish --build
