name: github_release

on:
  push:
    tags:
      - "*"


jobs:
  github_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        persist-credentials: false
    - name: Install uv
      uses: astral-sh/setup-uv@v7
    - name: Prepare release notes
      run: uvx git-cliff -l -s all > release-notes.md
    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        body_path: release-notes.md